"""Pricing Engine Sidecar package.

Pure deterministic financial math engine conforming to FCS v2.6.
"""

from src.pricing_sidecar.arithmetic import (
    PRECISION,
    ROUNDING_RULE,
    assert_no_float,
    forbid_float,
    format_vnd,
    round_vnd,
    safe_rate_amount,
    sum_rates,
    to_decimal,
)
from src.pricing_sidecar.contracts import (
    CANONICAL_SCENARIO_ORDER,
    SCENARIO_ALIAS_MAP,
    VALID_BENEFIT_MAPPING,
    AntiFloatBaseModel,
    BenefitApplicationRule,
    BenefitCategory,
    BenefitType,
    CalculationBase,
    CalculationStatus,
    CashflowInstallmentOutput,
    InstallmentRule,
    OptimizationObjective,
    PaymentScenarioConfig,
    PolicyDecisionStatus,
    PricingCalculationInput,
    PricingCalculationOutput,
    QuoteWorkflowStatus,
    RecommendationResult,
    ScenarioCalculationResult,
    ScenarioType,
    StructuredPolicyReference,
    ValidationReport,
    ValuationStatus,
    create_canonical_scenario_config,
    create_pa_chudong_config,
    create_pa_nhanh_config,
    create_pa_vay_config,
)

__all__ = [
    "CANONICAL_SCENARIO_ORDER",
    "PRECISION",
    "ROUNDING_RULE",
    "SCENARIO_ALIAS_MAP",
    "VALID_BENEFIT_MAPPING",
    "AntiFloatBaseModel",
    "BenefitApplicationRule",
    "BenefitCategory",
    "BenefitType",
    "CalculationBase",
    "CalculationStatus",
    "CashflowInstallmentOutput",
    "InstallmentRule",
    "OptimizationObjective",
    "PaymentScenarioConfig",
    "PolicyDecisionStatus",
    "PricingCalculationInput",
    "PricingCalculationOutput",
    "QuoteWorkflowStatus",
    "RecommendationResult",
    "ScenarioCalculationResult",
    "ScenarioType",
    "StructuredPolicyReference",
    "ValidationReport",
    "ValuationStatus",
    "assert_no_float",
    "create_canonical_scenario_config",
    "create_pa_chudong_config",
    "create_pa_nhanh_config",
    "create_pa_vay_config",
    "forbid_float",
    "format_vnd",
    "round_vnd",
    "safe_rate_amount",
    "sum_rates",
    "to_decimal",
]
